---
title: "covid 2"
output: html_notebook
---


library
```{r}
library(htmltab)
library(stringr)
library(magrittr)
library(rio)
```


Scrapping
```{r}
library(htmltab) 

link = "https://coronavirus.jhu.edu/data/mortality"
linkPath='//*[@id="root"]/div/div[2]/div/div/div/div/div[1]/div[2]/div[3]/div/table'

covid = htmltab(doc = link, 
                which =linkPath)

```

Cambiando nombres
```{r}
names(covid)=c("Country","cases","deads","mortality","deads per 100k person")
```

Reseteando filas
```{r}
row.names(covid)=NULL 

```


Limpiando tabla: 
```{r}

#Casos
covid$cases=gsub(',',"",covid$cases) #reemplazo coma por punto y convierto a numérico
covid$cases=as.numeric(covid$cases)

#muertos
covid$deads=gsub(',',"",covid$deads)  #reemplazo coma por punto y convierto a numérico
covid$deads=as.numeric(covid$deads)

#mortalidad
covid$mortality=str_split(covid$mortality,   
                         pattern = '%',
                         simplify = T)[,1]  #separo porcentaje y me quedo con el número

covid$mortality=as.numeric(covid$mortality)


#muertos por 100 k
covid$`deads per 100k person`=as.numeric(covid$`deads per 100k person`) #convertir a numérico

#verificando estructura
str(covid)
```
descargando datos a github
```{r}
write.csv(covid,"covid.csv", row.names = F)
```

